version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 15
    commit-message:
      prefix: "fix(deps)"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 15
    commit-message:
      prefix: "fix(deps)"
    groups:
      kube:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
      gomod:
        patterns:
          - "*"
        exclude-patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
