//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kontinuum) DeepCopyInto(out *Kontinuum) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kontinuum.
func (in *Kontinuum) DeepCopy() *Kontinuum {
	if in == nil {
		return nil
	}
	out := new(Kontinuum)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kontinuum) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KontinuumConfigStatus) DeepCopyInto(out *KontinuumConfigStatus) {
	*out = *in
	out.Server = in.Server
	out.Log = in.Log
	out.OIDC = in.OIDC
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KontinuumConfigStatus.
func (in *KontinuumConfigStatus) DeepCopy() *KontinuumConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KontinuumConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KontinuumList) DeepCopyInto(out *KontinuumList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kontinuum, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KontinuumList.
func (in *KontinuumList) DeepCopy() *KontinuumList {
	if in == nil {
		return nil
	}
	out := new(KontinuumList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KontinuumList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KontinuumLogConfigStatus) DeepCopyInto(out *KontinuumLogConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KontinuumLogConfigStatus.
func (in *KontinuumLogConfigStatus) DeepCopy() *KontinuumLogConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KontinuumLogConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KontinuumOIDCConfigStatus) DeepCopyInto(out *KontinuumOIDCConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KontinuumOIDCConfigStatus.
func (in *KontinuumOIDCConfigStatus) DeepCopy() *KontinuumOIDCConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KontinuumOIDCConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KontinuumSecretReference) DeepCopyInto(out *KontinuumSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KontinuumSecretReference.
func (in *KontinuumSecretReference) DeepCopy() *KontinuumSecretReference {
	if in == nil {
		return nil
	}
	out := new(KontinuumSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KontinuumServerConfigStatus) DeepCopyInto(out *KontinuumServerConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KontinuumServerConfigStatus.
func (in *KontinuumServerConfigStatus) DeepCopy() *KontinuumServerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KontinuumServerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KontinuumSpec) DeepCopyInto(out *KontinuumSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KontinuumSpec.
func (in *KontinuumSpec) DeepCopy() *KontinuumSpec {
	if in == nil {
		return nil
	}
	out := new(KontinuumSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KontinuumStatus) DeepCopyInto(out *KontinuumStatus) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	out.SecretRef = in.SecretRef
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KontinuumStatus.
func (in *KontinuumStatus) DeepCopy() *KontinuumStatus {
	if in == nil {
		return nil
	}
	out := new(KontinuumStatus)
	in.DeepCopyInto(out)
	return out
}
